services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z
      - ./sites:/etc/caddy/sites:z
      - caddy_data:/data
      - caddy_config:/config
      - /var/log/caddy:/var/log/caddy:z

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    name: caddy-proxy
    external: true
