// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: associations.sql

package database

import (
	"context"
)

const getAssociations = `-- name: GetAssociations :one

SELECT id, name, address, administrator, created_at, updated_at from associations where id = ?
`

func (q *Queries) GetAssociations(ctx context.Context, id int64) (Association, error) {
	row := q.db.QueryRowContext(ctx, getAssociations, id)
	var i Association
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Administrator,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
