// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: categories.sql

package database

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const bulkDeactivateCategories = `-- name: BulkDeactivateCategories :exec
UPDATE categories
SET is_deleted = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN (/*SLICE:category_ids*/?)
  AND association_id = ?
`

type BulkDeactivateCategoriesParams struct {
	CategoryIds   []int64
	AssociationID int64
}

func (q *Queries) BulkDeactivateCategories(ctx context.Context, arg BulkDeactivateCategoriesParams) error {
	query := bulkDeactivateCategories
	var queryParams []interface{}
	if len(arg.CategoryIds) > 0 {
		for _, v := range arg.CategoryIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:category_ids*/?", strings.Repeat(",?", len(arg.CategoryIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:category_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.AssociationID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const bulkReactivateCategories = `-- name: BulkReactivateCategories :exec
UPDATE categories
SET is_deleted = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN (/*SLICE:category_ids*/?)
  AND association_id = ?
`

type BulkReactivateCategoriesParams struct {
	CategoryIds   []int64
	AssociationID int64
}

func (q *Queries) BulkReactivateCategories(ctx context.Context, arg BulkReactivateCategoriesParams) error {
	query := bulkReactivateCategories
	var queryParams []interface{}
	if len(arg.CategoryIds) > 0 {
		for _, v := range arg.CategoryIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:category_ids*/?", strings.Repeat(",?", len(arg.CategoryIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:category_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.AssociationID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const checkCategoryUniqueness = `-- name: CheckCategoryUniqueness :one
SELECT COUNT(*) as count
FROM categories
WHERE association_id = ?
  AND type = ?
  AND family = ?
  AND name = ?
  AND is_deleted = FALSE
  AND (? = 0 OR id != ?)
`

type CheckCategoryUniquenessParams struct {
	AssociationID int64
	Type          string
	Family        string
	Name          string
	Column5       interface{}
	ID            int64
}

func (q *Queries) CheckCategoryUniqueness(ctx context.Context, arg CheckCategoryUniquenessParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCategoryUniqueness,
		arg.AssociationID,
		arg.Type,
		arg.Family,
		arg.Name,
		arg.Column5,
		arg.ID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (type, family, name, association_id, original_labels)
VALUES (?, ?, ?, ?, ?) RETURNING id, type, family, name, is_deleted, association_id, created_at, updated_at, original_labels
`

type CreateCategoryParams struct {
	Type           string
	Family         string
	Name           string
	AssociationID  int64
	OriginalLabels sql.NullString
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Type,
		arg.Family,
		arg.Name,
		arg.AssociationID,
		arg.OriginalLabels,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Family,
		&i.Name,
		&i.IsDeleted,
		&i.AssociationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalLabels,
	)
	return i, err
}

const deactivateCategory = `-- name: DeactivateCategory :exec
UPDATE categories
SET is_deleted = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) DeactivateCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateCategory, id)
	return err
}

const getActiveCategories = `-- name: GetActiveCategories :many
SELECT id, type, family, name, is_deleted, association_id, created_at, updated_at, original_labels
FROM categories
WHERE association_id = ?
  AND is_deleted = FALSE
ORDER BY type, family, name
`

// When retrieving categories, filter out deleted ones
func (q *Queries) GetActiveCategories(ctx context.Context, associationID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getActiveCategories, associationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Family,
			&i.Name,
			&i.IsDeleted,
			&i.AssociationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, type, family, name, is_deleted, association_id, created_at, updated_at, original_labels
FROM categories
WHERE association_id = ?
  AND (? = TRUE OR is_deleted = FALSE)
ORDER BY is_deleted ASC, type, family, name
`

type GetAllCategoriesParams struct {
	AssociationID int64
	Column2       interface{}
}

func (q *Queries) GetAllCategories(ctx context.Context, arg GetAllCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories, arg.AssociationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Family,
			&i.Name,
			&i.IsDeleted,
			&i.AssociationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssociationCategory = `-- name: GetAssociationCategory :one
SELECT id, type, family, name, is_deleted, association_id, created_at, updated_at, original_labels
FROM categories
WHERE id = ? and association_id = ? LIMIT 1
`

type GetAssociationCategoryParams struct {
	ID            int64
	AssociationID int64
}

func (q *Queries) GetAssociationCategory(ctx context.Context, arg GetAssociationCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getAssociationCategory, arg.ID, arg.AssociationID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Family,
		&i.Name,
		&i.IsDeleted,
		&i.AssociationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalLabels,
	)
	return i, err
}

const getCategoriesForDropdown = `-- name: GetCategoriesForDropdown :many
SELECT id, name
FROM categories
WHERE association_id = ?
  AND is_deleted = FALSE
ORDER BY name
`

type GetCategoriesForDropdownRow struct {
	ID   int64
	Name string
}

// When retrieving categories for dropdown lists, filter out deleted ones
func (q *Queries) GetCategoriesForDropdown(ctx context.Context, associationID int64) ([]GetCategoriesForDropdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesForDropdown, associationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesForDropdownRow
	for rows.Next() {
		var i GetCategoriesForDropdownRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, type, family, name, is_deleted, association_id, created_at, updated_at, original_labels
FROM categories
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Family,
		&i.Name,
		&i.IsDeleted,
		&i.AssociationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalLabels,
	)
	return i, err
}

const getCategoryUsageCount = `-- name: GetCategoryUsageCount :one
SELECT COUNT(*) as usage_count
FROM expenses
WHERE category_id = ?
`

func (q *Queries) GetCategoryUsageCount(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCategoryUsageCount, categoryID)
	var usage_count int64
	err := row.Scan(&usage_count)
	return usage_count, err
}

const getCategoryUsageDetails = `-- name: GetCategoryUsageDetails :many
SELECT id, description, amount, date, created_at
FROM expenses
WHERE category_id = ?
ORDER BY date DESC
LIMIT 10
`

type GetCategoryUsageDetailsRow struct {
	ID          int64
	Description string
	Amount      float64
	Date        time.Time
	CreatedAt   sql.NullTime
}

func (q *Queries) GetCategoryUsageDetails(ctx context.Context, categoryID int64) ([]GetCategoryUsageDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryUsageDetails, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryUsageDetailsRow
	for rows.Next() {
		var i GetCategoryUsageDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Date,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isCategoryActive = `-- name: IsCategoryActive :one
SELECT EXISTS(SELECT 1
              FROM categories
              WHERE id = ?
                AND is_deleted = FALSE) as is_active
`

// In all expense endpoints, validate that the category is not deleted
func (q *Queries) IsCategoryActive(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isCategoryActive, id)
	var is_active int64
	err := row.Scan(&is_active)
	return is_active, err
}

const reactivateCategory = `-- name: ReactivateCategory :exec
UPDATE categories
SET is_deleted = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND association_id = ?
`

type ReactivateCategoryParams struct {
	ID            int64
	AssociationID int64
}

func (q *Queries) ReactivateCategory(ctx context.Context, arg ReactivateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, reactivateCategory, arg.ID, arg.AssociationID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET type = ?,
    family = ?,
    name = ?,
    original_labels = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND association_id = ?
RETURNING id, type, family, name, is_deleted, association_id, created_at, updated_at, original_labels
`

type UpdateCategoryParams struct {
	Type           string
	Family         string
	Name           string
	OriginalLabels sql.NullString
	ID             int64
	AssociationID  int64
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.Type,
		arg.Family,
		arg.Name,
		arg.OriginalLabels,
		arg.ID,
		arg.AssociationID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Family,
		&i.Name,
		&i.IsDeleted,
		&i.AssociationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalLabels,
	)
	return i, err
}
