// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: member_invitations.sql

package database

import (
	"context"
	"time"
)

const createMemberInvitation = `-- name: CreateMemberInvitation :one
INSERT INTO member_invitations (
    gathering_id,
    owner_id,
    token_hash,
    expires_at
) VALUES (?, ?, ?, ?)
RETURNING id, gathering_id, owner_id, token_hash, expires_at, revoked_at, created_at, updated_at
`

type CreateMemberInvitationParams struct {
	GatheringID int64
	OwnerID     int64
	TokenHash   string
	ExpiresAt   time.Time
}

func (q *Queries) CreateMemberInvitation(ctx context.Context, arg CreateMemberInvitationParams) (MemberInvitation, error) {
	row := q.db.QueryRowContext(ctx, createMemberInvitation,
		arg.GatheringID,
		arg.OwnerID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i MemberInvitation
	err := row.Scan(
		&i.ID,
		&i.GatheringID,
		&i.OwnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveMemberInvitationByOwnerAndGathering = `-- name: GetActiveMemberInvitationByOwnerAndGathering :one
SELECT id, gathering_id, owner_id, token_hash, expires_at, revoked_at, created_at, updated_at
FROM member_invitations
WHERE gathering_id = ?
  AND owner_id = ?
  AND revoked_at IS NULL
LIMIT 1
`

type GetActiveMemberInvitationByOwnerAndGatheringParams struct {
	GatheringID int64
	OwnerID     int64
}

func (q *Queries) GetActiveMemberInvitationByOwnerAndGathering(ctx context.Context, arg GetActiveMemberInvitationByOwnerAndGatheringParams) (MemberInvitation, error) {
	row := q.db.QueryRowContext(ctx, getActiveMemberInvitationByOwnerAndGathering, arg.GatheringID, arg.OwnerID)
	var i MemberInvitation
	err := row.Scan(
		&i.ID,
		&i.GatheringID,
		&i.OwnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberInvitationByTokenHash = `-- name: GetMemberInvitationByTokenHash :one
SELECT id, gathering_id, owner_id, token_hash, expires_at, revoked_at, created_at, updated_at
FROM member_invitations
WHERE token_hash = ?
  AND revoked_at IS NULL
  AND expires_at > datetime('now')
LIMIT 1
`

func (q *Queries) GetMemberInvitationByTokenHash(ctx context.Context, tokenHash string) (MemberInvitation, error) {
	row := q.db.QueryRowContext(ctx, getMemberInvitationByTokenHash, tokenHash)
	var i MemberInvitation
	err := row.Scan(
		&i.ID,
		&i.GatheringID,
		&i.OwnerID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemberInvitationsByGathering = `-- name: ListMemberInvitationsByGathering :many
SELECT id, gathering_id, owner_id, token_hash, expires_at, revoked_at, created_at, updated_at
FROM member_invitations
WHERE gathering_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListMemberInvitationsByGathering(ctx context.Context, gatheringID int64) ([]MemberInvitation, error) {
	rows, err := q.db.QueryContext(ctx, listMemberInvitationsByGathering, gatheringID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberInvitation
	for rows.Next() {
		var i MemberInvitation
		if err := rows.Scan(
			&i.ID,
			&i.GatheringID,
			&i.OwnerID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMemberInvitation = `-- name: RevokeMemberInvitation :exec
UPDATE member_invitations
SET revoked_at = datetime('now'),
    updated_at = datetime('now')
WHERE id = ?
  AND revoked_at IS NULL
`

func (q *Queries) RevokeMemberInvitation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, revokeMemberInvitation, id)
	return err
}
