// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            int64
	Number        string
	Destination   string
	Description   string
	IsActive      bool
	AssociationID int64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type ActiveOwnerUnit struct {
	OwnerID             int64
	OwnerName           string
	OwnerNormalizedName string
	OwnerIdentification string
	OwnerContactEmail   string
	OwnerContactPhone   string
	UnitID              int64
	CadastralNumber     string
	UnitNumber          string
	Area                float64
	VotingWeight        float64
	UnitType            string
	Floor               int64
	Entrance            int64
	BuildingID          int64
	BuildingName        string
	BuildingAddress     string
	AssociationID       int64
	OwnershipID         int64
}

type Association struct {
	ID            int64
	Name          string
	Address       string
	Administrator string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Building struct {
	ID              int64
	Name            string
	Address         string
	CadastralNumber string
	TotalArea       float64
	AssociationID   int64
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Category struct {
	ID            int64
	Type          string
	Family        string
	Name          string
	IsDeleted     bool
	AssociationID int64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Expense struct {
	ID          int64
	Amount      float64
	Description string
	Destination string
	Date        time.Time
	Month       int64
	Year        int64
	CategoryID  int64
	AccountID   int64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DocumentRef sql.NullString
}

type Gathering struct {
	ID                          int64
	AssociationID               int64
	Title                       string
	Description                 string
	Intent                      string
	GatheringDate               time.Time
	GatheringType               string
	Status                      string
	QualificationUnitTypes      sql.NullString
	QualificationFloors         sql.NullString
	QualificationEntrances      sql.NullString
	QualificationCustomRule     sql.NullString
	QualifiedUnitsCount         sql.NullInt64
	QualifiedUnitsTotalPart     sql.NullFloat64
	QualifiedUnitsTotalArea     sql.NullFloat64
	ParticipatingUnitsCount     sql.NullInt64
	ParticipatingUnitsTotalPart sql.NullFloat64
	ParticipatingUnitsTotalArea sql.NullFloat64
	CreatedAt                   sql.NullTime
	UpdatedAt                   sql.NullTime
}

type GatheringParticipant struct {
	ID                        int64
	GatheringID               int64
	ParticipantType           string
	ParticipantName           string
	ParticipantIdentification sql.NullString
	OwnerID                   sql.NullInt64
	DelegatingOwnerID         sql.NullInt64
	DelegationDocumentRef     sql.NullString
	UnitsInfo                 string
	UnitsArea                 float64
	UnitsPart                 float64
	CheckInTime               sql.NullTime
	CreatedAt                 sql.NullTime
	UpdatedAt                 sql.NullTime
}

type Owner struct {
	ID                   int64
	Name                 string
	NormalizedName       string
	IdentificationNumber string
	ContactPhone         string
	ContactEmail         string
	FirstDetectedAt      sql.NullTime
	AssociationID        int64
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type Ownership struct {
	ID                   int64
	UnitID               int64
	OwnerID              int64
	AssociationID        int64
	StartDate            sql.NullTime
	EndDate              sql.NullTime
	IsActive             bool
	RegistrationDocument string
	RegistrationDate     time.Time
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	IsVoting             bool
}

type PasswordResetToken struct {
	Token     string
	Login     string
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    sql.NullTime
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Login     string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type RegistrationToken struct {
	Token       string
	CreatedBy   string
	CreatedAt   time.Time
	ExpiresAt   time.Time
	UsedAt      sql.NullTime
	UsedBy      sql.NullString
	RevokedAt   sql.NullTime
	RevokedBy   sql.NullString
	Description string
	IsAdmin     bool
}

type Unit struct {
	ID              int64
	CadastralNumber string
	BuildingID      int64
	UnitNumber      string
	Address         string
	Entrance        int64
	Area            float64
	Part            float64
	UnitType        string
	Floor           int64
	RoomCount       int64
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type UnitSlot struct {
	ID            int64
	GatheringID   int64
	UnitID        int64
	ParticipantID interface{}
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type User struct {
	ID           int64
	Login        string
	PasswordHash string
	ToptSecret   string
	IsAdmin      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UsersAssociation struct {
	ID            int64
	UserID        int64
	AssociationID int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type VoteTally struct {
	ID             int64
	GatheringID    int64
	VotingMatterID int64
	TallyData      string
	LastUpdated    sql.NullTime
}

type VotingAuditLog struct {
	ID          int64
	GatheringID int64
	EntityType  string
	EntityID    int64
	Action      string
	PerformedBy sql.NullString
	PerformedAt sql.NullTime
	IpAddress   sql.NullString
	Details     sql.NullString
}

type VotingBallot struct {
	ID                   int64
	GatheringID          int64
	ParticipantID        int64
	BallotContent        string
	BallotHash           string
	SubmittedAt          sql.NullTime
	SubmittedIp          sql.NullString
	SubmittedUserAgent   sql.NullString
	Signature            sql.NullString
	SignatureTimestamp   sql.NullTime
	SignatureCertificate sql.NullString
	IsValid              sql.NullBool
	InvalidatedAt        sql.NullTime
	InvalidationReason   sql.NullString
}

type VotingMatter struct {
	ID           int64
	GatheringID  int64
	OrderIndex   int64
	Title        string
	Description  sql.NullString
	MatterType   string
	VotingConfig string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type VotingNotification struct {
	ID               int64
	GatheringID      int64
	OwnerID          int64
	NotificationType string
	SentAt           sql.NullTime
	SentVia          sql.NullString
	ReadAt           sql.NullTime
}
