// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            int64
	Number        sql.NullString
	Destination   sql.NullString
	Description   sql.NullString
	AssociationID sql.NullInt64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Association struct {
	ID            int64
	Name          sql.NullString
	Address       sql.NullString
	Administrator sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Building struct {
	ID              int64
	Name            sql.NullString
	Address         sql.NullString
	CadastralNumber sql.NullString
	TotalArea       sql.NullFloat64
	AssociationID   sql.NullInt64
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Category struct {
	ID            int64
	Type          sql.NullString
	Family        sql.NullString
	Name          sql.NullString
	AssociationID sql.NullInt64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Expense struct {
	ID          int64
	Amount      sql.NullFloat64
	Description sql.NullString
	Destination sql.NullString
	Date        sql.NullTime
	Month       sql.NullInt64
	Year        sql.NullInt64
	CategoryID  sql.NullInt64
	AccountID   sql.NullInt64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Owner struct {
	ID                   int64
	Name                 string
	NormalizedName       string
	IdentificationNumber sql.NullString
	ContactPhone         sql.NullString
	ContactEmail         sql.NullString
	FirstDetectedAt      sql.NullTime
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type Ownership struct {
	ID                   int64
	UnitID               int64
	OwnerID              int64
	StartDate            sql.NullTime
	EndDate              interface{}
	IsActive             sql.NullBool
	RegistrationDocument sql.NullString
	RegistrationDate     sql.NullTime
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Login     string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Unit struct {
	ID              int64
	CadastralNumber sql.NullString
	BuildingID      string
	UnitNumber      sql.NullString
	Address         sql.NullString
	Area            float64
	Part            float64
	UnitType        sql.NullString
	Floor           sql.NullInt64
	RoomCount       sql.NullInt64
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type User struct {
	ID           int64
	Login        string
	PasswordHash string
	ToptSecret   string
	IsAdmin      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UsersAssociation struct {
	ID            int64
	UserID        int64
	AssociationID int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
