// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            int64
	Number        string
	Destination   string
	Description   string
	IsActive      bool
	AssociationID int64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Association struct {
	ID            int64
	Name          string
	Address       string
	Administrator string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Building struct {
	ID              int64
	Name            string
	Address         string
	CadastralNumber string
	TotalArea       float64
	AssociationID   int64
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Category struct {
	ID            int64
	Type          string
	Family        string
	Name          string
	IsDeleted     bool
	AssociationID int64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Expense struct {
	ID          int64
	Amount      float64
	Description string
	Destination string
	Date        time.Time
	Month       int64
	Year        int64
	CategoryID  int64
	AccountID   int64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DocumentRef sql.NullString
}

type Gathering struct {
	ID                          int64
	AssociationID               int64
	Title                       string
	Description                 string
	Intent                      string
	GatheringDate               time.Time
	GatheringType               string
	Status                      string
	QualificationUnitTypes      sql.NullString
	QualificationFloors         sql.NullString
	QualificationEntrances      sql.NullString
	QualificationCustomRule     sql.NullString
	QualifiedUnitsCount         sql.NullInt64
	QualifiedUnitsTotalPart     sql.NullFloat64
	ParticipatingUnitsCount     sql.NullInt64
	ParticipatingUnitsTotalPart sql.NullFloat64
	CreatedAt                   sql.NullTime
	UpdatedAt                   sql.NullTime
}

type GatheringNotification struct {
	ID               int64
	GatheringID      int64
	OwnerID          int64
	NotificationType string
	SentAt           sql.NullTime
	ReadAt           sql.NullTime
	ResponseStatus   sql.NullString
}

type GatheringParticipant struct {
	ID                        int64
	GatheringID               int64
	UnitID                    int64
	ParticipantType           string
	ParticipantName           string
	ParticipantIdentification sql.NullString
	OwnerID                   sql.NullInt64
	OwnershipID               sql.NullInt64
	DelegatingOwnerID         sql.NullInt64
	DelegationDocumentRef     sql.NullString
	UnitNumber                string
	UnitBuildingName          string
	UnitVotingWeight          float64
	CheckInTime               sql.NullTime
	VotingCompleted           sql.NullBool
	CreatedAt                 sql.NullTime
	UpdatedAt                 sql.NullTime
}

type Owner struct {
	ID                   int64
	Name                 string
	NormalizedName       string
	IdentificationNumber string
	ContactPhone         string
	ContactEmail         string
	FirstDetectedAt      sql.NullTime
	AssociationID        int64
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
}

type Ownership struct {
	ID                   int64
	UnitID               int64
	OwnerID              int64
	AssociationID        int64
	StartDate            sql.NullTime
	EndDate              sql.NullTime
	IsActive             bool
	RegistrationDocument string
	RegistrationDate     time.Time
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	IsVoting             bool
}

type PasswordResetToken struct {
	Token     string
	Login     string
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    sql.NullTime
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Login     string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type RegistrationToken struct {
	Token       string
	CreatedBy   string
	CreatedAt   time.Time
	ExpiresAt   time.Time
	UsedAt      sql.NullTime
	UsedBy      sql.NullString
	RevokedAt   sql.NullTime
	RevokedBy   sql.NullString
	Description string
	IsAdmin     bool
}

type Unit struct {
	ID              int64
	CadastralNumber string
	BuildingID      int64
	UnitNumber      string
	Address         string
	Entrance        int64
	Area            float64
	Part            float64
	UnitType        string
	Floor           int64
	RoomCount       int64
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type User struct {
	ID           int64
	Login        string
	PasswordHash string
	ToptSecret   string
	IsAdmin      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UsersAssociation struct {
	ID            int64
	UserID        int64
	AssociationID int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Vote struct {
	ID             int64
	GatheringID    int64
	ParticipantID  int64
	VotingMatterID int64
	VotingOptionID sql.NullInt64
	VoteValue      sql.NullString
	VoteWeight     float64
	SubmittedAt    sql.NullTime
}

type VoteAuditLog struct {
	ID          int64
	VoteID      int64
	Action      string
	PerformedBy sql.NullString
	PerformedAt sql.NullTime
	IpAddress   sql.NullString
	UserAgent   sql.NullString
	Details     sql.NullString
}

type VotingMatter struct {
	ID                      int64
	GatheringID             int64
	OrderIndex              int64
	Title                   string
	Description             sql.NullString
	MatterType              string
	VotingType              string
	RequiredMajorityType    string
	RequiredMajorityValue   float64
	RequiredQuorum          sql.NullFloat64
	IsAnonymous             sql.NullBool
	ShowResultsDuringVoting sql.NullBool
	AllowAbstention         sql.NullBool
	IsLocked                sql.NullBool
	LockedAt                sql.NullTime
	CreatedAt               sql.NullTime
	UpdatedAt               sql.NullTime
}

type VotingOption struct {
	ID             int64
	VotingMatterID int64
	OptionText     string
	OrderIndex     int64
	CreatedAt      sql.NullTime
}
