// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: revoked_tokens.sql

package database

import (
	"context"
	"time"
)

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT EXISTS(
    SELECT 1 FROM revoked_tokens
    WHERE jti = ? AND expires_at > datetime('now')
) AS revoked
`

func (q *Queries) IsTokenRevoked(ctx context.Context, jti string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isTokenRevoked, jti)
	var revoked int64
	err := row.Scan(&revoked)
	return revoked, err
}

const purgeExpiredRevokedTokens = `-- name: PurgeExpiredRevokedTokens :exec
DELETE FROM revoked_tokens WHERE expires_at <= datetime('now')
`

func (q *Queries) PurgeExpiredRevokedTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeExpiredRevokedTokens)
	return err
}

const revokeToken = `-- name: RevokeToken :exec
INSERT INTO revoked_tokens (jti, expires_at) VALUES (?, ?)
`

type RevokeTokenParams struct {
	Jti       string
	ExpiresAt time.Time
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeToken, arg.Jti, arg.ExpiresAt)
	return err
}
